export const MenuCodes = {
  Dashboard: 'DASHBOARD',
  Schools: 'SCHOOLS',
  Users: 'USERS',
  Roles: 'ROLES',
  Settings: 'SETTINGS',
  Academics: 'ACADEMICS',
  AcademicSetup: 'ACADEMIC_SETUP',
  FeesManagement: 'FEES_MANAGEMENT',
  SalaryManagement: 'SALARY_MANAGEMENT',
  LeaveManagement: 'LEAVE_MANAGEMENT',
  Administration: 'ADMINISTRATION',
  Reports: 'REPORTS',
  Students: 'STUDENTS',
  Employees: 'EMPLOYEES',
  Classes: 'CLASSES',
  ClassMappings: 'CLASS_MAPPINGS',
  Subjects: 'SUBJECTS',
  AcademicYears: 'ACADEMIC_YEARS',
  Attendance: 'ATTENDANCE',
  AttendanceReport: 'ATTENDANCE_REPORT',
  Homework: 'HOMEWORK',
  FeesStructure: 'FEES_STRUCTURE',
  FeesClassAmounts: 'FEES_CLASS_AMOUNTS',
  FeesCollection: 'FEES_COLLECTION',
  SalaryStructure: 'SALARY_STRUCTURE',
  SalaryEmployees: 'SALARY_EMPLOYEES',
  SalaryPayroll: 'SALARY_PAYROLL',
  LeaveStaff: 'LEAVE_STAFF',
  LeaveStudent: 'LEAVE_STUDENT',
  MyActions: 'MY_ACTIONS',
  FrontOffice: 'FRONT_OFFICE',
  VisitorBook: 'VISITOR_BOOK',
  PhoneLogs: 'PHONE_LOGS',
  Complaints: 'COMPLAINTS',
  AdmissionInquiries: 'ADMISSION_INQUIRIES',
  FrontOfficeSetup: 'FRONT_OFFICE_SETUP',
  Notices: 'NOTICES',
} as const;

export type MenuCode = (typeof MenuCodes)[keyof typeof MenuCodes];
